[package]
name = "autoui"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["dylib"]

[dependencies]
auto-lang = { workspace = true }
auto-val = { workspace = true }
autogui = { workspace = true }
gpui = { workspace = true }
