
// Auto-generated runnable example
// Generated by: auto-ui-transpile run
// This file can be deleted after the application exits

use auto_ui::{Component, View};

// ===== Generated Component Code =====
// Auto-generated from Auto language
// DO NOT EDIT - changes will be overwritten


#[derive(Debug)]
pub struct Counter {
    pub count: i32,
}

impl Counter {
    pub fn new(count: i32) -> Self {
        Self {
            count,
        }
    }
}

impl Component for Counter {
    type Msg = i32;

    fn on(&mut self, msg: Self::Msg) {
        match msg {
            1 => {
            }
            2 => {
            }
            _ => {}
        }
    }

    fn view(&self) -> View<Self::Msg> {
        View::col().spacing(0).padding(0)
    .child(View::button("+", 1))
    .child(View::text(&self.count.to_string()))
    .child(View::button("-", 2))
    .build()
    }
}



// ===== Default Implementation =====
impl Default for Counter {
    fn default() -> Self {
        // Create component with default values
        Self::new(
            "Hello from Auto!".to_string(),
        )
    }
}

// ===== Main Function =====
fn main() -> auto_ui::AppResult<()> {
    println!("╔════════════════════════════════════════════════════════════╗");
    println!("║        AutoUI Quick Run                              ║");
    println!("╚════════════════════════════════════════════════════════════╝");
    println!();
    println!("📝 Component: Counter");
    println!("🚀 Running AutoUI application with gpui backend...");
    println!();

    auto_ui_gpui::run_app::<Counter>("AutoUI - Counter")
}
