[package]
name = "autoui-theme"
version = "0.1.0"
edition = "2021"

[dependencies]
gpui = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
paste = { workspace = true }
anyhow = { workspace = true }
once_cell = { workspace = true }