[package]
name = "auto-iced"
version = "0.1.0"
edition = "2024"

[dependencies]
auto-lang = { workspace = true }
auto-val = { workspace = true }
auto-atom = { workspace = true }
iced = { workspace = true }