[package]
name = "gpui-dynamic"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["dylib"]

[dependencies]
# gpui = { git = "https://github.com/zed-industries/zed" }
gpui = { git = "https://github.com/huacnlee/zed.git", branch = "webview" }

