[package]
name = "gpui-components-examples"
version = "0.1.0"
edition = "2024"

[dependencies]
auto-ui = { workspace = true }
gpui = { workspace = true }
gpui-component = { workspace = true }
gpui-story = { workspace = true }
markdown = { workspace = true }